language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - 2.5.0
  - ruby-head

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
   code_climate:
     repo_token: aaa2bcd71ac641474a13caabe294beeb26abcc7c4dd82f3395a7b9193bb20d02

